### ISSUE TITLE
[ LV-ViT-S Pretrained Model ]

### ISSUE THREAD

**Issue by IemProg** [raoyongming/DynamicViT#13]
Hi, 

Thanks for the wonderful work.
Could you share with us the password to unzip LV-ViT-S pretrained model (original) ?

Thanks !

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. The file name may be a bit confusing.  The `*.pth.tar` is already the checkpoint file of the LVViT model (not the compressed version of the checkpoint file). You can direct load this file using `torch.load` without uncompression.
