### ISSUE TITLE
GFLOPs and Throughput

### ISSUE THREAD

**Issue by AmeenAli** [raoyongming/DynamicViT#14]
Hi,
Thanks sharing this awesome work,
can you elaborate more on how you measure the GFLOPs and Throughput reported in the experiments ?
Thanks,

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. We measure the FLOPs by manually writing down the complexity of each type of layer and summing them up using a simple script. The throughput is measured on a single 3090 GPU with batch size fixed to 32.

**Comment by shadowpa0327** [comment]
I thinks the flops can be calculate using the `fvcore`. Just add `model.eval()` before you invoke the `FlopCountAnalysis` function.
