### ISSUE TITLE
DynamicVIT training stored checkpoint

### ISSUE THREAD

**Issue by SwapnilDreams100** [raoyongming/DynamicViT#18]
Hi, thanks for the great work! I am training the dvit for the deit-small, and the checkpoint it stored has size of 364 MB, while the original model and the weights you shared are ~90MB.
Am I making an error?

**Comment by raoyongming** [comment]
Hi, thanks for your interest in our work. We remove the parameters of the optimizer and ema models from the checkpoints we shared to reduce the file size. Therefore, it is normal that the checkpoints created by the training script are larger.

**Comment by SwapnilDreams100** [comment]
ah makes sense, thanks!
