### ISSUE TITLE
关于Attention Masking创新点的疑问

### ISSUE THREAD

**Issue by xmu-xiaoma666** [raoyongming/DynamicViT#3]
关于论文中Attention Masking，对于这个创新点有比较大的疑惑。因为个人觉得只需要根据mask，把token的内容置位-inf就可以了，不需要交互结束之后，再在softmax过程中加上用mask进行制约。

另外，这篇文章提出的方法是不是只能在预测的时候减少计算量，因为在训练的时候进行Self-Attention，还是所有token都进行了Self-Attention，这样的文中的计算量就没有下降。反而因为加入了预测模块，计算量还上升了。

**Comment by xxkkrr** [comment]
你好，想再问一下关于保留mask可导的细节，像是类似于score = score + (1 - mask) *  -100000这样的实现方式是可导的吗，看起来这个式子里对于mask的导数就是score的导数/100000？
