### ISSUE TITLE
Dynamic token on training speedup

### ISSUE THREAD

**Issue by ZK-Zhou** [raoyongming/DynamicViT#38]
Hi Yongming,

Thank you for your wonderful work, I would like to ask if dynamic vit will achieve speedup during training (vs vanilla ViT).

**Comment by raoyongming** [comment]
Hi @ZK-Zhou, thanks for your interest in our work. DynamicViT is designed for model acceleration during inference. Since we drop tokens based on their importance predicted by a well pre-trained model, our method cannot be directly used to speed up training.
