### ISSUE TITLE
Pretrain LV-ViT-S and LV-ViT-M

### ISSUE THREAD

**Issue by kristenkn** [raoyongming/DynamicViT#4]
Hi Yongming,

Thanks for sharing your excellent work. 

I tried to downloaded the pretrain model, but it seems the provided link of LV-ViT-S and LV-ViT-M models inside the [download_pretrain.sh](https://github.com/raoyongming/DynamicViT/blob/master/download_pretrain.sh) file are not available, will you be able to share them in here?

Thank you

**Comment by raoyongming** [comment]
Hi @kristenkn, thanks for your interest in our work. I have uploaded the pre-trained models used in our experiments to Tsinghua Cloud and Google Drive, and updated the README.
