### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper_scatter__value)

### ISSUE THREAD

**Issue by King4819** [raoyongming/DynamicViT#44]
Hi, when I change args --device to 'cuda:1', it gives me this error

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper_scatter__value)

Thanks!!!

**Comment by raoyongming** [comment]
Hi, in our codebase, `args.device` should always be `cuda`. If you want to specify a GPU to run the code, you could use the environment variable like `CUDA_VISIBLE_DEVICES=1`.

**Comment by King4819** [comment]
@raoyongming Thanks for your reply !!!
