### ISSUE TITLE
pretrained model download

### ISSUE THREAD

**Issue by dirtycomputer** [raoyongming/DynamicViT#7]
`!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1iZc6d27EuEnlfUpJoNhsZEkt6GVgPy7-' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1iZc6d27EuEnlfUpJoNhsZEkt6GVgPy7-" -O lvvit_m-56M-224-84.0.tar && rm -rf /tmp/cookies.txt`
I can use the code above download lvvit_m-56M-224-84.0.tar
But why I can't use
`!tar -xvf lvvit_m-56M-224-84.0.tar`
to extract the file
It says 
> tar: This does not look like a tar archive
> tar: Skipping to next header
> tar: Exiting with failure status due to previous errors

**Comment by raoyongming** [comment]
Hi @dirtycomputer, 

`lvvit_m-56M-224-84.0.tar` is the checkpoint file of the pretrained model. You can directly use `torch.load('lvvit_m-56M-224-84.0.tar')' to load the pretrained model. You don't need to untar the file.

**Comment by dirtycomputer** [comment]
Tks
